{% set name = "ocw" %}
{% set version = "1.2.0" %}
{% set sha256 = "134497701503e38f48c677ce37f06f29b0a3372faafaba0d0810c7ba38d10d96" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  fn: {{ name }}-{{ version }}.tar.gz
  url: https://github.com/apache/climate/archive/master.tar.gz
  sha256: {{ sha256 }}

build:
  number: 0
  script: python setup.py install --single-version-externally-managed --record record.txt

requirements:
  build:
    - python
    - setuptools
  run:
    - python
    - numpy
    - scipy
    - matplotlib
    - basemap
    - netcdf4
    - h5py
    - bottle
    - pydap
    - python-dateutil
    - myproxyclient # [not py3k]
    - esgf-pyclient # [not py3k]
    - podaacpy >= 1.9.0

test:
  imports:
    - ocw
    - ocw.data_source
    - ocw.esgf

about:
  home: http://climate.apache.org/
  license: Apache 2.0
  license_file: LICENSE.txt
  license_family: Apache
  summary: 'A library for simplifying the process of climate model evaluation.'
  doc_url: http://cwiki.apache.org/confluence/display/CLIMATE
  dev_url: https://github.com/apache/climate

extra:
  recipe-maintainers:
    - agoodm
    - jarifibrahim
