travis:
  secure:
    BINSTAR_TOKEN: cMd3yTfOrX85Jo/EiySpjbaKFKaoYFI66I5e53thz10u+yr8+5NfECGgmKF7qKw3hz2/wnmdY9aMYfbTp8yXBOLywKBQuXvpLeFpg88eHus9zqYCM50iS4KnGj5J08VojxKQZYsMomM76CdpzqkcfTvRiXfqXmEi6Zu/4evoryLoH41/YY26SFjAmYmzkvGXwYq4CXw/T43EzyuToWF4JO+dq32NoVT5yTA0fcVOat8Ak9IBJd7N3st4i4VvgINdJWcdmAZZ6+2m3geJgChm9DzMhsqgzeZ3MKoQypRFjkTjViEgiVQ79m/GEZRuEQE+c4b4mPljPKJQKuDGWrTLDifvozu7DNeiL5gesKtlIV2+dCjYO9ANT7vu5bXgAKmS6cdRZPbP7xtNbUG5iR1c1ZJD43gdQObOA9gDc/MO0kdRMNb0mKn81vdcizM7R00kDhhk3Eo6M+EPStsPQ6n/u6H0nAVDWonvbW+AJId3nx9IVzSSwcamWL7EyEI6O6qfXIxqg4tG23CFOVNhirfuXWj1xA6t6TQrm/IlK5wrwqrc6mRWpbjwr6ZFOjVkBzt/dxr4hahlQkp/+5Dx8frrRXSSMy3Yc942LoGfMhVP+418qX5Jg8cbk1wTA45WwQN5E+wZbZR+CPLeEX00/CHR8sLlKWVP6HAhWUPAvCqICPc=
appveyor:
  secure:
    BINSTAR_TOKEN: ipv/06DzgA7pzz2CIAtbPxZSsphDtF+JFyoWRnXkn3O8j7oRe3rzqj3LOoq2DZp4
