appveyor:
  secure: {BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1}
compiler_stack: comp7
max_py_ver: '37'
max_r_ver: '35'
travis:
  secure: {BINSTAR_TOKEN: RhELNbhMeAIjcCiZoPGVOqaxAAQr0t61tGMYIyR0+DcxCpzZ0Xpvy87h2tSd5bXwxOVcGrgIlD869TrQMIjxCLrh/LNWX+1deGqHG5aEYExbSw/qC/PPxMP0oarTfCytiWlQZyjbUBZMAte0No27P+2PS4Q71AlCRg6Em+AvEqpJefjdy384ZcDHWoCbjhhCwFSfZFa8pBbH+iPPEZ4xoZezS0IVVjU8WPpJuDDIYD7n19v4ebyEZM9mh6wK80agOH4fcdnIEXR9CnW9RYjye2yE0fOi0mrUkQUNBcvd1JHsc4yghse/N9fzMumzP0Fd/JUVGrBTwci9dYNhVbGxWnq/YqDn2UNFLiFaxU347w0qh60BSZikvDP7oZrv4lXaZDimF30WiGsy047+qC5HwwWeacPiTh6LMf0K4yRJNZ9TP5A+lR3Yp5MOd0U/CSDgrx5Xj8rG6HevlzZns4iDUS1SRSk1nzs2rf0Me0WbIn5PYUkXuSmwyGaRTCEkRI+doy3WmLcBKiMBOa2Gh0sbtvf8/HSKXWZGKxOaixItaheeH8Hw6OR7WyQ7iA9mfUiWkE8BWJKdY19jMP6a1wx5XoRPCSSij3TYBpRQ9BgkUp2WBrs5KljFp7wy4PIQasWTdpO0o9dqOK3IZ0rMMcYVd8D2BJsiHjkrWlb1rTxGnUA=}
